import React,{useState} from 'react';
import {ChevronLeft,ChevronRight,X,MapPin} from 'lucide-react';
import {places,journey,projectPoint,routePath} from '@/data/journey';
import {landPaths} from '@/data/worldMap';
export default function JourneyMap({language}){
 const zh=language==='zh';const [selected,setSelected]=useState(null);const [eventIndex,setEventIndex]=useState(null);const now=new Date().toISOString().slice(0,10);
 const place=places.find(p=>p.id===selected);const events=journey.filter(e=>e.place===selected);const activeEvent=eventIndex===null?null:journey[eventIndex];
 const selectPlace=id=>{setSelected(id);setEventIndex(null)};const step=direction=>{const i=eventIndex===null?(direction>0?0:journey.length-1):(eventIndex+direction+journey.length)%journey.length;setEventIndex(i);setSelected(journey[i].place)};
 const date=e=>zh?(e.dateZh||e.date):e.date;
 return <section id="journey" className="section shell journey-section"><div className="section-heading"><div><p className="eyebrow">04 / {zh?'在路上':'Places & people'}</p><h2>{zh?'我的旅程':'My journey'}</h2></div><p>{zh?'学习、研究与实践留下的坐标。':'A record of learning, research, and practice.'}</p></div><div className="journey-card surface"><div className="map-toolbar"><span>2020—2027</span><span className="map-instruction">{zh?'点击地点查看经历':'Select a place to see the story'}</span><div className="map-legend"><span><i/>{zh?'已发生':'Visited'}</span><span><i className="dashed"/>{zh?'计划':'Upcoming'}</span></div></div><div className="map-viewport" onKeyDown={e=>{if(e.key==='Escape'){setSelected(null);setEventIndex(null)}}}>
 <svg viewBox="0 0 1000 500" role="group" aria-label={zh?'按时间连接十座城市的世界地图':'World map connecting ten cities in chronological order'}>
 <defs><clipPath id="map-clip"><rect width="1000" height="500"/></clipPath></defs><g clipPath="url(#map-clip)"><g className="map-land">{landPaths.map((d,i)=><path d={d} key={i}/>)}</g><g className="map-graticule">{[125,250,375].map(y=><path key={y} d={`M0 ${y}H1000`}/>)}</g><g fill="none">{journey.slice(1).map((e,i)=>{const a=places.find(p=>p.id===journey[i].place),b=places.find(p=>p.id===e.place);return <path key={e.id} d={routePath(a.coords,b.coords)} className={'journey-route '+(e.start>now?'is-future ':'')+(eventIndex===i+1?'is-selected':'')}><title>{date(journey[i])+' '+a[language]+' → '+date(e)+' '+b[language]}</title></path>})}</g><text x="335" y="340" className="ocean-label">ATLANTIC OCEAN</text><text x="58" y="305" className="ocean-label">PACIFIC OCEAN</text><text x="638" y="355" className="ocean-label">INDIAN OCEAN</text>
 {places.map(p=>{const point=projectPoint(p.coords),pin=p.pin||point;const future=journey.filter(e=>e.place===p.id).every(e=>e.start>now);return <g key={p.id} className={'map-place '+(selected===p.id?'is-active ':'')+(future?'is-future':'')} role="button" tabIndex="0" aria-label={p[language]+': '+journey.filter(e=>e.place===p.id).map(e=>date(e)+' '+(zh?e.zh:e.en)).join('; ')} aria-expanded={selected===p.id} aria-controls="journey-detail" onClick={()=>selectPlace(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectPlace(p.id)}}}>
 {p.pin&&<path className="pin-leader" d={`M${point[0]} ${point[1]}L${pin[0]} ${pin[1]}`}/>}<circle cx={pin[0]} cy={pin[1]} r="18" className="pin-hit"/><circle cx={pin[0]} cy={pin[1]} r="9" className="pin-halo"/><circle cx={pin[0]} cy={pin[1]} r="4" className="pin-core"/><text x={p.label[0]} y={p.label[1]} textAnchor={p.label[0]<pin[0]?'end':'start'}>{p[language]}</text></g>})}</g></svg>
 </div><div className="journey-bottom"><div className="journey-context"><MapPin size={15}/><span>{zh?'10 座城市 · 按起始时间连线':'10 places · Connected by start date'}</span></div><div className="journey-stepper"><button aria-label={zh?'上一段经历':'Previous event'} onClick={()=>step(-1)}><ChevronLeft size={17}/></button><span>{eventIndex===null?(zh?'时间顺序':'Chronological'):`${String(eventIndex+1).padStart(2,'0')} / ${journey.length}`}</span><button aria-label={zh?'下一段经历':'Next event'} onClick={()=>step(1)}><ChevronRight size={17}/></button></div></div>
 <div className="city-selector" aria-label={zh?'选择城市':'Select a city'}>{places.map(p=><button key={p.id} onClick={()=>selectPlace(p.id)} aria-pressed={selected===p.id}>{p[language]}</button>)}</div>
 {place&&<div className="journey-detail" id="journey-detail" role="region" aria-label={place[language]} aria-live="polite"><div className="journey-detail-heading"><h3>{place[language]}<span>{zh?place.en:place.zh}</span></h3><button aria-label={zh?'关闭地点详情':'Close place details'} onClick={()=>{setSelected(null);setEventIndex(null)}}><X size={17}/></button></div><div className="journey-events">{(activeEvent?[activeEvent]:events).map(e=><article key={e.id}><div className="event-date">{date(e)}{e.start>now&&<span>{zh?'计划行程':'Upcoming'}</span>}{e.start<=now&&e.end>=now&&<span>{zh?'进行中':'Ongoing'}</span>}</div><h4>{zh?e.zh:e.en}</h4><p>{zh?e.detailZh:e.detailEn}</p></article>)}</div></div>}</div><p className="map-credit"><a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth</a> · {zh?'旅程示意，连线不代表实际交通路线':'Schematic connections; lines do not represent travel routes.'}</p></section>
}
