import React,{useState} from 'react';
const fields={
 embodied:{en:['Embodied interaction','Grounded in Hiroshi Ishii’s Tangible Bits: thinking through the body, physical objects, and the spaces around us.'],zh:['具身交互','以 Hiroshi Ishii 的 Tangible Bits 为理论基础，关注身体、实体物件与周围空间如何参与交互。']},
 multimodal:{en:['Multimodal intelligence','Connecting vision, language, and spatial data so AI can interpret objects and their relationships.'],zh:['多模态智能','连接视觉、语言与空间数据，让人工智能理解物体及其空间关系。']},
 generative:{en:['Generative experiences','Using generative methods to reshape spatial experiences while preserving how a place can be used.'],zh:['生成式体验','用生成式方法改变空间的感知与体验，同时保留空间原有的使用方式。']},
 spatial:{en:['Spatial intelligence','Where these directions meet: systems that understand space and support how people act and create within it.'],zh:['空间智能','三个方向的交汇：让系统理解空间，并支持人们在其中行动与创作。']}}
export default function ResearchVenn({language}){
 const [active,setActive]=useState(null); const zh=language==='zh'; const info=active?fields[active][language]:null;
 const events=id=>({role:'button',tabIndex:0,'aria-label':fields[id][language].join('. '),'aria-describedby':active===id?'venn-tooltip':undefined,onMouseEnter:()=>setActive(id),onFocus:()=>setActive(id),onClick:()=>setActive(id),onKeyDown:e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActive(id)}if(e.key==='Escape')setActive(null)}});
 return <div className="research-card surface" onMouseLeave={e=>{if(!e.currentTarget.contains(document.activeElement))setActive(null)}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setActive(null)}}><div className="card-eyebrow"><span>{zh?'研究方向':'Research focus'}</span><span className="micro-dot"/></div><svg viewBox="0 0 520 415" className="venn-svg" role="group" aria-label={zh?'三个研究方向交汇为空间智能':'Three research directions intersect at spatial intelligence'}>
 <defs><radialGradient id="v-blue"><stop stopColor="#eef8fc" stopOpacity=".74"/><stop offset="1" stopColor="#d6ebf7" stopOpacity=".54"/></radialGradient><radialGradient id="v-purple"><stop stopColor="#f4f0ff" stopOpacity=".74"/><stop offset="1" stopColor="#e4dcf6" stopOpacity=".50"/></radialGradient><radialGradient id="v-gold"><stop stopColor="#fff9ed" stopOpacity=".75"/><stop offset="1" stopColor="#f1e6c9" stopOpacity=".46"/></radialGradient></defs>
 <g {...events('embodied')} className={'venn-circle '+(active==='embodied'?'is-active':'')}><circle cx="200" cy="159" r="130" fill="url(#v-blue)" stroke="#c4dce9"/><text x="139" y="139"><tspan x="139">Embodied</tspan><tspan x="139" dy="22">interaction</tspan></text></g>
 <g {...events('multimodal')} className={'venn-circle '+(active==='multimodal'?'is-active':'')}><circle cx="320" cy="159" r="130" fill="url(#v-purple)" stroke="#d8cee9"/><text x="382" y="139"><tspan x="382">Multimodal</tspan><tspan x="382" dy="22">intelligence</tspan></text></g>
 <g {...events('generative')} className={'venn-circle '+(active==='generative'?'is-active':'')}><circle cx="260" cy="266" r="130" fill="url(#v-gold)" stroke="#e6dcc6"/><text x="260" y="323"><tspan x="260">Generative</tspan><tspan x="260" dy="22">experiences</tspan></text></g>
 <g {...events('spatial')} className="venn-center"><rect x="191" y="187" width="138" height="66" rx="22"/><text x="260" y="214"><tspan x="260">Spatial</tspan><tspan x="260" dy="22">intelligence</tspan></text></g>
 </svg><div className={'venn-note '+(info?'has-note':'')} aria-live="polite">{info?<div id="venn-tooltip" role="tooltip"><strong>{info[0]}</strong><p>{info[1]}</p>{active==='embodied'&&<a href="https://tangible.media.mit.edu/project/tangible-bits/" target="_blank" rel="noreferrer">Tangible Bits ↗</a>}</div>:<span>{zh?'悬停、点击或使用 Tab 查看方向说明':'Hover, tap, or tab to explore the intersections.'}</span>}</div></div>
}
